name: Build Void Sword Mod

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build mod
        run: ./gradlew build
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: voidsword-jar
          path: build/libs/*.jar
